services:

  database:
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sport_teh

  pizza-microservice:
    restart: unless-stopped
    build:
      context: ./pizza
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/pizza
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "5000:8082"
    depends_on:
      database:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M