spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5443/sport_tech
    username: postgres
    password: 1234

  sql:
    init:
      schema-locations: classpath:sql/db/schema.sql
      data-locations: classpath:sql/db/data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

path:
  image: SportProgam/src/main/resources/static/assets


front:
    ip: ${FRONT_IP}
    port: ${FRONT_PORT}
#security:
#  basic:
#    enable: false
#  ignored: /**
#
#management:
#  security:
#    enabled: false



