spring:
#  application:
#    name: pizza
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

    datasource:
        url: jdbc:postgresql://localhost:5433/sport_teh
        username: postgres
        password: 123

    jpa:
        hibernate:
            ddl-auto: update

    sql:
        init:
            data-locations: classpath:sql/db/data.sql
            mode: always

server:
  port: 8082

path:
  image: SportProgam/src/main/resources/static/assets


